# version: '3.8'

# services:
#   marzban:
#     build: .
#     restart: unless-stopped
#     ports:
#       - "8000:8000"
#     env_file: .env
#     environment:
#       - UVICORN_HOST=0.0.0.0
#       - UVICORN_PORT=8000
#       - XRAY_SUBSCRIPTION_URL_PREFIX=https://marz.timelessmovies.sbs
#       - SUDO_USERNAME=admin
#       - SUDO_PASSWORD=admin
#       - SQLALCHEMY_DATABASE_URL=sqlite:///var/lib/marzban/db.sqlite3
#     volumes:
#       - marzban_data:/var/lib/marzban
#       - marzban_config:/opt/marzban
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/api/system"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 40s

# volumes:
#   marzban_data:
#     driver: local
#   marzban_config:
#     driver: local


version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: marzban
      MYSQL_USER: marzban
      MYSQL_PASSWORD: marzbanpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  marzban:
    build: .
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - XRAY_SUBSCRIPTION_URL_PREFIX=https://marz.timelessmovies.sbs
      - SUDO_USERNAME=admin
      - SUDO_PASSWORD=admin
      - SQLALCHEMY_DATABASE_URL=mysql+asyncmy://marzban:marzbanpass@mysql:3306/marzban
    volumes:
      - marzban_data:/var/lib/marzban
      - marzban_config:/opt/marzban
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  marzban_data:
    driver: local
  marzban_config:
    driver: local
  mysql_data:
    driver: local
